config/routes.rb
Ulgood::Application.routes.draw do

  root to: "main#home"


  get 'auth/:provider', to: 'accounts#login', as: :login
  get 'auth/:provider/callback', to: 'accounts#login'


  resource :admins, only:[] do
    get 'users'
    get 'posts'
  end

  resource :admins, only:[] do
    get 'users'
    get 'posts'
  end

  resource :accounts, only:[] do
    collection do
      get 'login'
      get 'logout', as: :logout
    end
  end

  resources :goods, only: [:index, :create, :destroy] do
    member do
      get 'check'
    end
  end

  resources :users, only: [:show] do
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :avatar, :name, :admin

  has_many :accounts, :dependent => :destroy

  validates :name, presence: true
  validates :avatar, format: { with: /^https?:\/\/[\w\/\.]+(\.?(|jpe?g|gif|png)|picture[\?]?[\w\=\&]*)/ }, allow_nil: true

  def has_account_in(provider)
    self.accounts.find_by_provider(provider).present?
  end

  def goods
    self.accounts.map{|acc|acc.goods}.flatten.sort_by{|good| good.created_at}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter do
    redirect_to :root unless account_signed_in?
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_messages.html.haml
-messages = []
-User.find(params[:id]).social_accounts.each do |i|
  -i.messages.each do |m|
    -messages << m if m.checked? || current_social_account.user.id.to_s == params[:id]
-temp_date = 0
- if messages.count == 0
  <br>У пользователя ещё нет добрых дел.
-else
  -messages.reverse.each do |m|
    -if m.created_at.day != temp_date
      -temp_date = m.created_at.day
      .date
        ="#{m.created_at.day}.#{m.created_at.month}"
    .today_list_item{ :onclick => "#{"show_full(this);" if m.message.length > 50}", :style => "#{"cursor:pointer;" if m.message.length > 50}", :onmouseover => "showSocialButtons(this);", :onmouseout => "hideSocialButtons(this)" }
      =image_tag("#{m.social_account.provider}-small-icon.png")
      =raw "<span#{' style=color:#ccc' unless m.checked?}>"
      =m.message
      =raw "</span>"
      <span class = "social_post">
      =link_to image_tag("vkontakte-small-icon.png", :alt => "В"), "http://vkontakte.ru/share.php?url=#{root_url}&image=#{root_url}/assets/mic_logo.png&title=Ulgood.ru: #{m.social_account.user.name} #{m.message} via Ulgood.ru http://ulgood.ru/"
      </span>
      <span class = "social_post">
      =link_to image_tag("facebook-small-icon.png", :alt => "F"), "https://www.facebook.com/dialog/feed?app_id=188628294595434&link=#{root_url}&picture=http://ulgood.ru/assets/mic_logo.png&name=Ulgood.ru&caption=Ulgood.ru:&description=#{m.social_account.username} #{m.message} via Ulgood.ru http://ulgood.ru/&redirect_uri=http://ulgood.ru/"
      </span>
      <span class = "social_post">
      =link_to image_tag("twitter-small-icon.png", :alt => "T"), "https://twitter.com/intent/tweet?original_referer=#{request.fullpath}&related=Ulgood.ru&source=tweetbutton&text=Ulgood.ru: #{m.social_account.username} #{m.message} via Ulgood.ru http://ulgood.ru/ &url=#{root_url}"
      </span>

app/views/users/show.html.haml
-if flash[:notice]
  %span.label.label-success
    =flash[:notice]
.row
  .span2
    =image_tag @user.avatar || 'anonim.jpg', class: :avatar
  .span6
    .row
      %h1
        %p.text-orange
          =@user.name
    .row
      .social-panel
        -providers.each do |provider|
          -if @user.has_account_in provider
            %a{href: @user.accounts.find_by_provider(provider).url}
              =image_tag "#{provider}-icon.png"
          -else
            -if @user == current_user
              =link_to login_path(provider: provider) do
                =image_tag "#{provider}-icon-gray.png"
.row.goods
  .span8
    //-@user.goods.checked_with_date.each_pair do |date, goods|
    -@user.goods.group_by{|good| good.created_at.to_date}.each_pair do |date, goods|
      %p
        %span.date
          -if date == Date.today
            =t('today')
          -else
            =l(date)
      -goods.each do |good|
        %p{class: "#{'gray' unless good.checked?}"}
          \-
          =good.text
          -if @user == current_user
            =link_to(good_path(good.id), method: :delete) do
              x

app/views/users/show.js.haml
:plain
  $('header').html(#{render("layouts/header").to_json.html_safe})
  $('#main').html(#{render(:file => 'users/show.html.haml').to_json.html_safe})
  $('#main').css("top","60px")
  $('#posts').css("top",$(ava).height())