config/routes.rb
Ulgood::Application.routes.draw do

  root to: "main#home"


  get 'auth/:provider', to: 'accounts#login', as: :login
  get 'auth/:provider/callback', to: 'accounts#login'


  resource :admins, only:[] do
    get 'users'
    get 'posts'
  end

  resource :admins, only:[] do
    get 'users'
    get 'posts'
  end

  resource :accounts, only:[] do
    collection do
      get 'login'
      get 'logout', as: :logout
    end
  end

  resources :goods, only: [:index, :create, :destroy] do
    member do
      get 'check'
    end
  end

  resources :users, only: [:show] do
  end

end

app/views/layouts/_about.html.haml
.modal.hide#about{tabindex: -1, role: 'dialog', 'aria-labelledby' => 'Label', 'aria-hidden' => true}
  .modal-header
    %button.close{type: 'button', 'data-dismiss' => 'modal', 'aria-hidden' => true}
      x
    %h3#Label
      =t('about_head')
  .modal-body
    %p
      TODO: about information
      =#TODO: about information

app/views/layouts/_counters.html.haml
.row.counter-head
  =t('.good_deals')
.row.counter
  .span1
    .row.time
      =t('.today')
    .row.count
      =Good.today.checked.count
  .span1
    .row.time
      =t('.all')
    .row.count
      =Good.checked.count

app/views/layouts/_footer.html.haml
.footer
  =t('credits')
  |
  %a{href: '#about', role: 'button', 'data-toggle' => 'modal'}
    =t('about')
  =image_tag 'men.png', class: 'people'
=render 'layouts/about'

app/views/layouts/_header.html.haml
%header
  =render "layouts/user_panel" if social_account_signed_in?
  %span{style:"font-family:micfont;font-size:20px; z-index:10; position:absolute; top:10px; left:360px;"}
    beta
  = link_to(image_tag("mic_logo.png", :alt => "ulmic.ru"), "http://ulmic.ru", :id => "miclogo")
  = link_to("НИ ДНЯ БЕЗ ДОБРЫХ ДЕЛ!", root_url, :id => "header_text", :style => @head_style)
  =render "main/post_form" if social_account_signed_in? && controller_name!="users" && action_name!="about"
  =render "layouts/counters" if social_account_signed_in?
  .top_alpha_block{ :style => "#{"height:50px" if controller_name=="users" || !social_account_signed_in?}"}

app/views/layouts/_user_panel.html.haml
#user_panel
  .user_panel_button
    =link_to "Выход", destroy_social_account_session_path, :method => :delete
  .user_panel_button
    =link_to "Новые дела (#{Message.where(:checked => nil).count})", {:controller => :admin, :action => :issues} if current_social_account.user.admin?

  #user_name
    Здравствуйте,
    =link_to current_social_account.user.name, {:controller => "users", :action => "show", :id => current_social_account.user.id}, :remote => true
  %div{ :style => "clear: both;" }

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      =t :title
    = stylesheet_link_tag    'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body


  %body
    .container-fluid
      .navbar
        .navbar-inner
          %ul.nav
            %li
              .link-logo
                =link_to root_path do
                  =image_tag 'logo.png', class: 'logo'
                  .brand
                    =t('name')
          %ul.nav.user-panel
            %li
              =link_to user_path(current_user), class: 'user_link' do
                =image_tag current_user.avatar, class: 'ava_little' if current_user.avatar
                %span{class: "#{'orange' if current_user.admin?}"}=current_user.name
            -if current_user.admin?
              %li
                =link_to "#{t('.unchecked')}:#{Good.unchecked.count} ", posts_admins_path
            %li
              =link_to t('exit'), logout_accounts_path
    .row
      .span8.offset2
        =yield
      .span2.counters
        =render 'layouts/counters'
    =render 'layouts/footer'

app/views/layouts/not_logged.html.haml
!!! 5
%html
  %head
    %title
      =t('title')
    = stylesheet_link_tag    'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    .container-fluid
      .row-fluid.top_line
        .span2
          =image_tag "mic_logo_#{I18n.locale}.jpg", class: 'logo'
        .span8.offset2
          %h1.head_text
            =t('head').mb_chars.upcase
      = yield
    =render 'layouts/footer'